name: Auto-update NPM packages

on:
  workflow_dispatch: # When triggered manually
  schedule:
    - cron: "0 3 1 * *" # At 3am on first day of the month

permissions:
  contents: read

jobs:
  update-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update packages
        uses: Cazoo-uk/action-npm-update@v1
        with:
          github-token: ${{ secrets.CAZOO_PLATFORM_BOT_REPO_TOKEN }}
          node-version: 18
